#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
require_relative 'GetCharacter'

# ARGV = [add, foo]
command = ARGV[0]
character_name = ARGV[1]
character_server = ARGV[2]

params = {
  command: command,
  character: {
    name: character_name,
    server: character_server
  }
}

controller = BattleNetInfoController.new(params)
routes = { "add" => :create, "list" => :index, "remove" => :destroy }

if route = routes[command]
  controller.send route
else
  name = ARGV[0]
  server = ARGV[1]
  output = GetCharacter.new(name, server)
  output.print_character
end
