#!/usr/bin/env ruby

require_relative 'bootstrap_ar'

# ARGV = [add, foo]
command = ARGV[0]
character_name = ARGV[1]
character_server = ARGV[2]
character_progression = ARGV[3]

params = {
  command: command,
  character: {
    name: character_name,
    server: character_server,
    progression: character_progression
  }
}

controller = BattleNetInfoController.new(params)

routes = {
  "add" => :create,
  "list" => :index,
  "remove" => :destroy,
  "progression" => :progression
}

if route = routes[command]
  controller.send route
else
  name = ARGV[0]
  server = ARGV[1]
  output = BattleNetAPI.new(name, server)
  output.print_character
  output.print_ToT_progression
end
